name: "桌游项目评分分析"
version: "1.0"
description: "对桌游众筹项目进行热度、受欢迎度、传播率的综合评分分析"
author: "AI分析系统"
created_date: "2024-01-15"

template: |
  你是一位资深的桌游市场分析师，拥有丰富的众筹项目评估经验。请根据以下桌游众筹项目数据进行专业的市场分析和评分。

  ## 项目基本信息
  - 项目名称：{project_name}
  - 项目分类：{category}
  - 发起时间：{start_date}
  - 结束时间：{end_date}
  - 项目状态：{project_status}

  ## 众筹表现数据
  - 目标金额：{target_amount}元
  - 实际筹集：{raised_amount}元
  - 完成率：{completion_rate}%
  - 支持者数量：{backer_count}人
  - 众筹天数：{duration_days}天
  - 平均每日筹款：{daily_average}元

  ## 用户参与数据
  - 项目更新次数：{update_count}
  - 评论数量：{comment_count}
  - 收藏/关注数：{favorite_count}
  - 支持者/点赞数：{supporter_count}

  ## 发起人信息
  - 发起人粉丝数：{author_fans}
  - 发起人关注数：{author_following}
  - 发起人获赞数：{author_likes}
  - 历史项目经验：{author_experience}

  ## 项目内容质量
  - 项目详情图片数：{image_count}
  - 项目详情视频数：{video_count}
  - 回报档位数量：{reward_tiers}
  - 回报档位信息：{reward_details}

  ## 分析要求

  请按照以下三个维度对项目进行评分（0-100分制）：

  ### 1. 热度分数 (Heat Score)
  综合考虑：
  - 众筹表现（完成率、超额程度、筹款速度）
  - 参与热度（支持者数量、评论活跃度）
  - 传播效果（收藏数、分享度）
  - 时间因素（项目新鲜度、市场时机）

  ### 2. 受欢迎度分数 (Popularity Score)  
  综合考虑：
  - 用户认可度（支持者数量质量、完成率）
  - 社区反响（评论质量、用户互动）
  - 产品吸引力（回报设计、价值主张）
  - 发起人影响力（粉丝基础、历史表现）

  ### 3. 传播率分数 (Viral Score)
  综合考虑：
  - 社交传播潜力（分享性、话题性）
  - 媒体关注度（新闻价值、创新性）
  - 口碑效应（用户推荐、二次传播）
  - 市场影响力（行业地位、竞争优势）

  ## 输出格式要求

  请严格按照以下JSON格式输出分析结果：

  ```json
  {
    "heat_score": 85,
    "popularity_score": 78,
    "viral_score": 72,
    "overall_score": 78,
    "analysis_reason": "该项目在众筹表现上超出预期，完成率达到150%，显示出强劲的市场需求。项目更新频繁，用户互动活跃，体现了良好的运营能力。发起人具有一定的粉丝基础，为项目成功提供了保障。但在传播创新性方面略显不足，限制了病毒式传播的潜力。",
    "threat_level": "中",
    "key_insights": [
      "众筹表现优异，市场需求强劲",
      "用户参与度高，社区活跃",
      "发起人经验丰富，执行力强",
      "产品创新性有待提升"
    ],
    "competitive_advantages": [
      "优秀的众筹执行能力",
      "活跃的用户社区",
      "丰富的回报档位设计"
    ],
    "potential_risks": [
      "市场竞争激烈",
      "创新性不足",
      "传播范围有限"
    ],
    "market_position": "该项目在桌游众筹市场中处于中上游水平，具有一定的竞争优势，但需要在产品创新和市场传播方面加强。"
  }
  ```

  ## 评分标准参考

  **热度分数标准：**
  - 90-100分：现象级项目，引发行业关注
  - 80-89分：热门项目，表现优异
  - 70-79分：成功项目，达到预期
  - 60-69分：一般项目，基本达标
  - 60分以下：表现不佳，需要改进

  **威胁等级定义：**
  - 高：综合分数≥80，对竞品构成重大威胁
  - 中：综合分数60-79，具有一定竞争力
  - 低：综合分数<60，威胁程度较小

  请确保分析客观、专业，基于数据进行合理推断，避免主观臆测。

parameters:
  max_tokens: 2000
  temperature: 0.3
  top_p: 0.9
  frequency_penalty: 0.1
  presence_penalty: 0.1

validation_rules:
  - "输出必须是有效的JSON格式"
  - "所有分数必须在0-100范围内"
  - "analysis_reason长度不超过200字"
  - "key_insights数组包含3-5个要点"
  - "威胁等级必须是'高'、'中'、'低'之一"

examples:
  - input: "项目名称：《星际探索》桌游，完成率：200%，支持者：500人"
    output: "heat_score: 92, popularity_score: 88, viral_score: 75"
  - input: "项目名称：《小镇建设》，完成率：80%，支持者：50人"  
    output: "heat_score: 65, popularity_score: 62, viral_score: 58"
