# AI分析系统配置文件
# 支持多种AI服务商和配置选项

# AI服务配置
ai_services:
  # 主要服务商
  primary:
    provider: "openai"
    api_key: "${OPENAI_API_KEY}"  # 从环境变量读取
    base_url: "https://api.openai.com/v1"
    model: "gpt-3.5-turbo"
    max_tokens: 2000
    temperature: 0.3
    timeout: 30
    
  # 备用服务商
  fallback:
    provider: "azure"
    api_key: "${AZURE_OPENAI_KEY}"
    base_url: "${AZURE_OPENAI_ENDPOINT}"
    model: "gpt-35-turbo"
    max_tokens: 2000
    temperature: 0.3
    timeout: 30
    
  # 国产大模型示例
  domestic:
    provider: "qianwen"
    api_key: "${QIANWEN_API_KEY}"
    base_url: "https://dashscope.aliyuncs.com/api/v1"
    model: "qwen-turbo"
    max_tokens: 2000
    temperature: 0.3
    timeout: 30

# 请求设置
request_settings:
  max_retries: 3
  retry_delay: 1  # 秒
  rate_limit: 60  # 每分钟请求数
  batch_size: 5   # 批量处理大小
  
# 分析配置
analysis_config:
  # 评分权重
  scoring_weights:
    funding_performance: 0.35   # 众筹表现
    user_engagement: 0.25       # 用户参与度
    social_impact: 0.20         # 社交影响力
    project_quality: 0.20       # 项目质量
    
  # 时间段定义（天数）
  time_periods:
    two_weeks: 14
    one_month: 30
    three_months: 90
    six_months: 180
    one_year: 365
    three_years: 1095
    
  # 威胁等级阈值
  threat_levels:
    high: 80      # 综合分数>=80为高威胁
    medium: 60    # 综合分数60-79为中威胁
    low: 0        # 综合分数<60为低威胁
    
  # 筛选条件
  filter_criteria:
    min_funding_amount: 1000     # 最小众筹金额（元）
    min_backer_count: 10         # 最小支持者数量
    exclude_categories: []       # 排除的分类
    
# 报告配置
report_config:
  # 输出格式
  output_format: "txt"
  encoding: "utf-8"
  
  # 报告结构
  sections:
    - "executive_summary"      # 执行摘要
    - "historical_analysis"    # 历史全量分析
    - "three_year_trends"      # 3年趋势
    - "one_year_hotspots"      # 1年热点
    - "six_month_emerging"     # 6个月新兴
    - "three_month_dynamics"   # 3个月动态
    - "one_month_latest"       # 1个月最新
    - "two_week_immediate"     # 2周即时
    
  # 每个时间段显示的项目数量
  top_projects_count:
    historical_analysis: 20
    three_year_trends: 15
    one_year_hotspots: 10
    six_month_emerging: 8
    three_month_dynamics: 6
    one_month_latest: 5
    two_week_immediate: 3
    
# 数据处理配置
data_config:
  # 输入文件设置
  input:
    excel_file: "摩点众筹-主要信息.xls"
    encoding: "utf-8"
    
  # 输出设置
  output:
    json_file: "data/processed/projects_data.json"
    cache_file: "data/cache/analysis_cache.json"
    
  # 数据清洗规则
  cleaning_rules:
    remove_test_projects: true
    min_title_length: 2
    max_title_length: 100
    invalid_amount_threshold: 0
    
# 日志配置
logging:
  level: "INFO"
  file: "logs/ai_analysis.log"
  max_size: "10MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# 缓存配置
cache:
  enabled: true
  ttl: 86400  # 缓存有效期（秒），24小时
  max_size: 1000  # 最大缓存项目数
  
# 安全配置
security:
  api_key_encryption: false  # 是否加密存储API密钥
  rate_limit_strict: true    # 是否严格执行速率限制
  data_anonymization: false  # 是否对敏感数据匿名化
